apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2VyCg==            # must encoded in base64 first
  mongo-password: bW9uZ29wYXNzd29yZAo=      # must encoded in base64 first
